name: CI App

on:
  pull_request:
    branches:
      - main
    paths:
      - app/**/*
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci-app:    
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install NPM packages
      run: npm run ci:app

    - name: Check Formatting
      run: npm run format:check:app

    - name: Lint
      run: npm run lint:app
    
    - name: Build project
      run: npm run build:app
