name: CI

on:
  pull_request:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:    
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install NPM packages
      run: npm ci

    - name: Check Formatting
      run: npm run format:check

    - name: Lint
      run: npm run lint
    
    - name: Build project
      run: npm run build
