name: Deploy App

on:
  push:
    branches:
      - main
    paths:
      - app/**
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    name: Test & Build Artifact
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install NPM packages
      run: npm run ci:app
    
    - name: Build project
      run: npm run build:app --production
      env:
        REACT_APP_FIREBASE_URL: ${{ secrets.FIREBASE_URL }}

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: ./app/build/
  
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: build
        path: ./build

    - name: Azure login
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Clean out blob storage account
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob delete-batch --account-name arumidesign -s '$web' --auth-mode key --pattern "*"

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name arumidesign --auth-mode key -d '$web' -s ./build
            
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "arumi-design-cdn-profile" --name "arumidesign" --resource-group "arumi-design"
    
    - name: Azure logout
      run: |
            az logout
