name: Deploy

on:
  push:
    branches:
      - main
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    name: Test & Build Artifact
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: npm run build

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: ./build/
  
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment:
      name: production
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: build

    - name: Azure login
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Clean out blob storage account
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob delete-batch --source `$web --account-name arumidesign --pattern "*"

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name arumidesign --auth-mode key -d '$web' -s .
            
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "arumi-design-cdn-profile" --name "arumidesign" --resource-group "arumi-design"
    
    - name: Azure logout
      run: |
            az logout
